### ISSUE TITLE
Xtreme3D 4.0 Milestone II

### ISSUE THREAD

**Issue by gecko0307** [xtreme3d/xtreme3d#65]
The second milestone is to port all extended functionality (custom classes that were written for Xtreme3D 3.x fork of GLScene).

Priority I:
- [x] TextureEx system
- [x] LightFX system
- [x] GLSLShader
- [x] PhongShader
- [x] BumpShader
- [x] ShadowMap
- [x] HUDShape
- [x] TTFont
- [x] FBO
- [x] ClipPlane

Priority II:
- [x] Extended sprite functions
- [x] ActorProxy individual animations
- [x] Linear water waves
- [x] DCE: set velocity and impulse
- [x] ODE: set velocity and position
- [x] Viewer: render to PNG
- [x] Kraft

Priority III:
- [x] CSM file loader
- [x] LOD file loader
